### ISSUE TITLE
Own Firebase backend

### ISSUE THREAD

**Issue by FurkanSimsir** [iangthomas/Ride-Sharing#5]
Hi, 
I want to use my own Firebase backend for this app. I tried changing the GoogleService-Info.plist file but that's not enough because the app doesn't work if I do so. How do I migrate this project to my own Firebase backend?

**Comment by iangthomas** [comment]
Hello! Thanks for your interest and question. Did you change the bundle id in your info.plst to match your app's bundle id in Firebase?
Best, Ian

**Comment by FurkanSimsir** [comment]
Hi, Thanks for your response! I didn't change it on the info.plist. I will test it again that way. So I don't have to do anything on the Firebase side?
